name: CI/CD Pipeline for NestJS Demo Project

on:
  push:
    branches: [main]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nestjs-demo-project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: nestjs-demo-project/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run : |
            docker build -t ghcr.io/${{github.repository}}/nestjs-demo-project:${{github.sha}} .
            docker tag ghcr.io/${{github.repository}}/nestjs-demo-project:${{github.sha}} ghcr.io/${{github.repository}}/nestjs-demo-project:latest

      - name: Push Image
        run: |
            docker push ghcr.io/${{github.repository}}/nestjs-demo-project:${{github.sha}}
            docker push ghcr.io/${{github.repository}}/nestjs-demo-project:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Multiple commands
      uses: appleboy/ssh-action@v1
      with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           port: ${{ secrets.PORT }}
           script: |
                cd /root/app
                docker-compose stop nestjs-app
                docker-compose rm -f nestjs-app
                docker rmi ghcr.io/rafaynadeem1203/nestjs-demo/nestjs-demo-project:latest || true
                docker-compose pull nestjs-app
                docker-compose up -d nestjs-app